Fix rustup HOME directory mismatch in Go container CI jobs
In the test-go-container job, GitHub Actions sets HOME=/github/home inside
containers, but the running user (root) has its actual home at /root. This
causes rustup to fail with:
  error: $HOME differs from euid-obtained home directory

Fix by setting HOME=/root via $GITHUB_ENV in the 'Install git' step for
amazon-linux containers, before rustup is invoked by install-shared-dependencies.

Closes #6081

Signed-off-by: Thomas Zhou <thomaszhou64@gmail.com>